# Generated by Django 5.1.4 on 2024-12-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='liked_users',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='da.buyer'),
            preserve_default=False,
        ),
    ]
