# Generated by Django 5.1.4 on 2024-12-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0002_remove_postmodel_liked_users_postmodel_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='da.buyer'),
        ),
    ]
