# Generated by Django 5.1.4 on 2024-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0003_remove_postmodel_liked_users_postmodel_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsectionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
