# Generated by Django 5.1.4 on 2025-01-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0004_alter_commentsectionmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsectionmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.postmodel'),
        ),
    ]
