# Generated by Django 5.1.4 on 2025-01-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0005_alter_commentsectionmodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
    ]
