# Generated by Django 5.1.4 on 2025-01-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='portrait',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='da.portraits'),
            preserve_default=False,
        ),
    ]
