# Generated by Django 5.1.4 on 2025-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0010_spam_delete_bannedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
